import { Surah, SurahListItem } from './types';

export const OFFLINE_SURAHS: Record<number, Surah> = {
  1: {
    number: 1,
    name: "سُورَةُ ٱلْفَاتِحَةِ",
    englishName: "Al-Fatihah",
    englishNameTranslation: "The Opening",
    revelationType: "Meccan",
    numberOfAyahs: 7,
    ayahs: [
      {
        number: 1,
        audio: "https://audio.qurancdn.com/Alafasy/mp3/001001.mp3",
        text: "بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ",
        translation: "In the name of Allah, the Entirely Merciful, the Especially Merciful.",
        tafsir: "<p><b>Tafsir Ibn Kathir:</b> <br/>The Surah is called Al-Fatihah, meaning 'The Opening' of the Book, because it is the first Surah recited in Salat (prayer) and the first written down by the copyists. It contains details about praising Allah, proclaiming His sovereignty, dedicating worship solely to Him, and seeking His guidance onto the straight path of the righteous.</p>",
        numberInSurah: 1,
        juz: 1,
        manzil: 1,
        page: 1,
        ruku: 1,
        hizbQuarter: 1,
        sajda: false
      },
      {
        number: 2,
        audio: "https://audio.qurancdn.com/Alafasy/mp3/001002.mp3",
        text: "ٱلْحَمْدُ لِلَّهِ رَبِّ ٱلْعَٰلَمِينَ",
        translation: "[All] praise is [due] to Allah, Lord of the worlds -",
        tafsir: "<p><b>Tafsir Ibn Kathir:</b> <br/>'Al-Hamdu lillah' expresses gratitude to Allah for His numerous favors on His servants. It acknowledges that Allah is the Creator, Sustainer, and Lord of all existence (the 'Worlds'), possessing sole authority over creation and command.</p>",
        numberInSurah: 2,
        juz: 1,
        manzil: 1,
        page: 1,
        ruku: 1,
        hizbQuarter: 1,
        sajda: false
      },
      {
        number: 3,
        audio: "https://audio.qurancdn.com/Alafasy/mp3/001003.mp3",
        text: "ٱلرَّحْمَٰنِ ٱلرَّحِيمِ",
        translation: "The Entirely Merciful, the Especially Merciful,",
        tafsir: "<p><b>Tafsir Ibn Kathir:</b> <br/>Ar-Rahman and Ar-Rahim are two names derived from 'Rahmah' (mercy). Ar-Rahman is more intensive, signifying mercy that encompasses all creation, while Ar-Rahim relates specifically to the special mercy He displays towards believers on the Day of Judgment.</p>",
        numberInSurah: 3,
        juz: 1,
        manzil: 1,
        page: 1,
        ruku: 1,
        hizbQuarter: 1,
        sajda: false
      },
      {
        number: 4,
        audio: "https://audio.qurancdn.com/Alafasy/mp3/001004.mp3",
        text: "مَٰلِكِ يَوْمِ ٱلدِّينِ",
        translation: "Sovereign of the Day of Recompense.",
        tafsir: "<p><b>Tafsir Ibn Kathir:</b> <br/>Allah clarifies His absolute sovereignty over the Day-of-Judgment (Yawm ad-Din), where every soul is fully recompensed. Directing obedience to Him now prepares the heart for that ultimate event of accountability.</p>",
        numberInSurah: 4,
        juz: 1,
        manzil: 1,
        page: 1,
        ruku: 1,
        hizbQuarter: 1,
        sajda: false
      },
      {
        number: 5,
        audio: "https://audio.qurancdn.com/Alafasy/mp3/001005.mp3",
        text: "إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ",
        translation: "It is You we worship and You we ask for help.",
        tafsir: "<p><b>Tafsir Ibn Kathir:</b> <br/>This verse represents the transition to direct address, indicating intimacy. 'We worship only You' signifies monotheistic sincerity (Ikhlas), and 'We ask only You for help' represents complete trust (Tawakkul) in His assistance.</p>",
        numberInSurah: 5,
        juz: 1,
        manzil: 1,
        page: 1,
        ruku: 1,
        hizbQuarter: 1,
        sajda: false
      },
      {
        number: 6,
        audio: "https://audio.qurancdn.com/Alafasy/mp3/001006.mp3",
        text: "ٱهْدِنَا ٱلصِّرَٰطَ ٱلْمُسْتَقِيمَ",
        translation: "Guide us to the straight path -",
        tafsir: "<p><b>Tafsir Ibn Kathir:</b> <br/>Guidance (Hidayah) is requested here: both the guidance of clarity/understanding and the guidance of steadfastness and success. The 'Straight Path' is Islam, the truth revealed through the Messenger of Allah.</p>",
        numberInSurah: 6,
        juz: 1,
        manzil: 1,
        page: 1,
        ruku: 1,
        hizbQuarter: 1,
        sajda: false
      },
      {
        number: 7,
        audio: "https://audio.qurancdn.com/Alafasy/mp3/001007.mp3",
        text: "صِرَٰطَ ٱلَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ ٱلْمَغْضُوبِ عَلَيْهِمْ وَلَا ٱلضَّآلِّينَ",
        translation: "The path of those upon whom You have bestowed favor, not of those who have earned [Your] anger or of those who are astray.",
        tafsir: "<p><b>Tafsir Ibn Kathir:</b> <br/>This verse defines the recipients of Allah's favors—the prophets, the truthful, the martyrs, and the righteous. It asks to shield believers from the paths of those who knew the truth but neglected it (earning anger), or those who acted in ignorance without guidance (astray).</p>",
        numberInSurah: 7,
        juz: 1,
        manzil: 1,
        page: 1,
        ruku: 1,
        hizbQuarter: 1,
        sajda: false
      }
    ]
  },
  112: {
    number: 112,
    name: "سُورَةُ ٱلْإِخْلَاصِ",
    englishName: "Al-Ikhlas",
    englishNameTranslation: "The Sincerity",
    revelationType: "Meccan",
    numberOfAyahs: 4,
    ayahs: [
      {
        number: 1,
        audio: "https://audio.qurancdn.com/Alafasy/mp3/112001.mp3",
        text: "قُلْ هُوَ ٱللَّهُ أَحَدٌ",
        translation: "Say, \"He is Allah, [who is] One,",
        tafsir: "<p><b>Tafsir Ibn Kathir:</b> <br/>Say: He is the One, the unique, who has no equal, no assistant, no rival, and no likeness. This name 'Al-Ahad' is not used for anyone else, representing the ultimate absolute unity of the Deity.</p>",
        numberInSurah: 1,
        juz: 30,
        manzil: 7,
        page: 604,
        ruku: 1,
        hizbQuarter: 120,
        sajda: false
      },
      {
        number: 2,
        audio: "https://audio.qurancdn.com/Alafasy/mp3/112002.mp3",
        text: "ٱللَّهُ ٱلصَّمَدُ",
        translation: "Allah, the Eternal Refuge.",
        tafsir: "<p><b>Tafsir Ibn Kathir:</b> <br/>As-Samad is the Master whose control is perfect, the One whom all of creation turns to, seeks, and depends on for their needs, while He Himself stands in need of nothing.</p>",
        numberInSurah: 2,
        juz: 30,
        manzil: 7,
        page: 604,
        ruku: 1,
        hizbQuarter: 120,
        sajda: false
      },
      {
        number: 3,
        audio: "https://audio.qurancdn.com/Alafasy/mp3/112003.mp3",
        text: "لَمْ يَلِدْ وَلَمْ يُولَدْ",
        translation: "He neither begets nor is born,",
        tafsir: "<p><b>Tafsir Ibn Kathir:</b> <br/>He has no children, no parents, and no spouse. This establishes He is peerless and eternal, untethered to cyclic creation, transcending any material, physical descent.</p>",
        numberInSurah: 3,
        juz: 30,
        manzil: 7,
        page: 604,
        ruku: 1,
        hizbQuarter: 120,
        sajda: false
      },
      {
        number: 4,
        audio: "https://audio.qurancdn.com/Alafasy/mp3/112004.mp3",
        text: "وَلَمْ يَكُن لَّهُۥ كُفُوًا أَحَدٌ",
        translation: "And there is none co-equal or comparable to Him.\"",
        tafsir: "<p><b>Tafsir Ibn Kathir:</b> <br/>He is beyond any conceptualization of peers or likeness. Absolutely nothing in creation resembles or equates to His greatness, power, or traits.</p>",
        numberInSurah: 4,
        juz: 30,
        manzil: 7,
        page: 604,
        ruku: 1,
        hizbQuarter: 120,
        sajda: false
      }
    ]
  },
  113: {
    number: 113,
    name: "سُورَةُ ٱلْفَلَقِ",
    englishName: "Al-Falaq",
    englishNameTranslation: "The Daybreak",
    revelationType: "Meccan",
    numberOfAyahs: 5,
    ayahs: [
      {
        number: 1,
        audio: "https://audio.qurancdn.com/Alafasy/mp3/113001.mp3",
        text: "قُلْ أَعُوذُ بِرَبِّ ٱلْفَلَقِ",
        translation: "Say, \"I seek refuge in the Lord of daybreak",
        tafsir: "<p><b>Tafsir Ibn Kathir:</b> <br/>Al-Falaq refers to the morning or daybreak. Seeking refuge in the Lord of daylight represents starting the day with absolute reliance on Allah's protection against dark harms.</p>",
        numberInSurah: 1,
        juz: 30,
        manzil: 7,
        page: 604,
        ruku: 1,
        hizbQuarter: 120,
        sajda: false
      },
      {
        number: 2,
        audio: "https://audio.qurancdn.com/Alafasy/mp3/113002.mp3",
        text: "مِن شَرِّ مَا خَلَقَ",
        translation: "From the evil of that which He created",
        tafsir: "<p><b>Tafsir Ibn Kathir:</b> <br/>This encompasses seeking safety from the physical or spiritual harms produced by any part of the creation—be it humans, jinn, beasts, or inanimate materials.</p>",
        numberInSurah: 2,
        juz: 30,
        manzil: 7,
        page: 604,
        ruku: 1,
        hizbQuarter: 120,
        sajda: false
      },
      {
        number: 3,
        audio: "https://audio.qurancdn.com/Alafasy/mp3/113003.mp3",
        text: "وَمِن شَرِّ غَاسِقٍ إِذَا وَقَبَ",
        translation: "And from the evil of darkness when it settles",
        tafsir: "<p><b>Tafsir Ibn Kathir:</b> <br/>'Ghasid' refers to the night when it covers everything with its density and darkness. Harms, plots, and hidden dangers thrive in darkness, making nighttime refuge central.</p>",
        numberInSurah: 3,
        juz: 30,
        manzil: 7,
        page: 604,
        ruku: 1,
        hizbQuarter: 120,
        sajda: false
      },
      {
        number: 4,
        audio: "https://audio.qurancdn.com/Alafasy/mp3/113004.mp3",
        text: "وَمِن شَرِّ ٱلنَّفَّٰثَٰتِ فِي ٱلْعُقَدِ",
        translation: "And from the evil of the blowers in knots",
        tafsir: "<p><b>Tafsir Ibn Kathir:</b> <br/>An allusion to practitioners of black magic, sorcery, and witchcraft who blow over knots to cast spells. This seeks barrier protection against external malicious intent and occult envy.</p>",
        numberInSurah: 4,
        juz: 30,
        manzil: 7,
        page: 604,
        ruku: 1,
        hizbQuarter: 120,
        sajda: false
      },
      {
        number: 5,
        audio: "https://audio.qurancdn.com/Alafasy/mp3/113005.mp3",
        text: "وَمِن شَرِّ حَاسِدٍ إِذَا حَسَدَ",
        translation: "And from the evil of an envier when he envies.\"",
        tafsir: "<p><b>Tafsir Ibn Kathir:</b> <br/>Seeking refuge from the destructive gaze or acts of envious people whose hearts burn at others' blessings. Envy is a lethal psychological and spiritual harm solved only by divine protection.</p>",
        numberInSurah: 5,
        juz: 30,
        manzil: 7,
        page: 604,
        ruku: 1,
        hizbQuarter: 120,
        sajda: false
      }
    ]
  },
  114: {
    number: 114,
    name: "سُورَةُ ٱلنَّاسِ",
    englishName: "An-Nas",
    englishNameTranslation: "The Mankind",
    revelationType: "Meccan",
    numberOfAyahs: 6,
    ayahs: [
      {
        number: 1,
        audio: "https://audio.qurancdn.com/Alafasy/mp3/114001.mp3",
        text: "قُلْ أَعُوذُ بِرَبِّ ٱلنَّاسِ",
        translation: "Say, \"I seek refuge in the Lord of mankind,",
        tafsir: "<p><b>Tafsir Ibn Kathir:</b> <br/>This Surah, along with Surah Al-Falaq, are the Mu'awwidhatayn (the two Surahs of protection). It frames Allah as 'Rabb' (the Lord/Nurturer) of humanity, establishing parental-like ultimate protection.</p>",
        numberInSurah: 1,
        juz: 30,
        manzil: 7,
        page: 604,
        ruku: 1,
        hizbQuarter: 120,
        sajda: false
      },
      {
        number: 2,
        audio: "https://audio.qurancdn.com/Alafasy/mp3/114002.mp3",
        text: "مَلِكِ ٱلنَّاسِ",
        translation: "The Sovereign of mankind,",
        tafsir: "<p><b>Tafsir Ibn Kathir:</b> <br/>Recognizing Him as Malik (King/Sovereign). This emphasizes He is the true ruler of rulers, who commands and governs the affairs of humanity directly.</p>",
        numberInSurah: 2,
        juz: 30,
        manzil: 7,
        page: 604,
        ruku: 1,
        hizbQuarter: 120,
        sajda: false
      },
      {
        number: 3,
        audio: "https://audio.qurancdn.com/Alafasy/mp3/114003.mp3",
        text: "إِلَٰهِ ٱلنَّاسِ",
        translation: "The God of mankind,",
        tafsir: "<p><b>Tafsir Ibn Kathir:</b> <br/>Declaring Him as 'Ilah'—the only deity worthy of devotion, worship, submissiveness, and request, whom mankind should look to in all matters.</p>",
        numberInSurah: 3,
        juz: 30,
        manzil: 7,
        page: 604,
        ruku: 1,
        hizbQuarter: 120,
        sajda: false
      },
      {
        number: 4,
        audio: "https://audio.qurancdn.com/Alafasy/mp3/114004.mp3",
        text: "مِن شَرِّ ٱلْوَسْوَاسِ ٱلْخَنَّاسِ",
        translation: "From the evil of the retreating whisperer -",
        tafsir: "<p><b>Tafsir Ibn Kathir:</b> <br/>Al-Waswas represents whisperers of doubts and bad deeds. Al-Khannas refers to how the whisperer retreats and vanishes immediately when the servant remembers Allah (Dhikr).</p>",
        numberInSurah: 4,
        juz: 30,
        manzil: 7,
        page: 604,
        ruku: 1,
        hizbQuarter: 120,
        sajda: false
      },
      {
        number: 5,
        audio: "https://audio.qurancdn.com/Alafasy/mp3/114005.mp3",
        text: "ٱلَّذِي يُوَسْوِسُ فِي صُدُورِ ٱلنَّاسِ",
        translation: "Who whispers [evil] into the breasts of mankind -",
        tafsir: "<p><b>Tafsir Ibn Kathir:</b> <br/>The whispering targets the 'breasts' or chests, representing the seat of emotions, decisions, and spirit, tempting them to divert from correct actions.</p>",
        numberInSurah: 5,
        juz: 30,
        manzil: 7,
        page: 604,
        ruku: 1,
        hizbQuarter: 120,
        sajda: false
      },
      {
        number: 6,
        audio: "https://audio.qurancdn.com/Alafasy/mp3/114006.mp3",
        text: "مِنَ ٱلْجِنَّةِ وَٱلنَّاسِ",
        translation: "From among the jinn and mankind.\"",
        tafsir: "<p><b>Tafsir Ibn Kathir:</b> <br/>Whisperers and corrupters exist among both unseen spirits (Jinn) and visible humans. This verse provides unified protection against both visible and invisible toxic influences.</p>",
        numberInSurah: 6,
        juz: 30,
        manzil: 7,
        page: 604,
        ruku: 1,
        hizbQuarter: 120,
        sajda: false
      }
    ]
  }
};

export const STATIC_SURAHS_LIST: SurahListItem[] = [
  { number: 1, name: "سُورَةُ ٱلْفَاتِحَةِ", englishName: "Al-Fatihah", englishNameTranslation: "The Opening", numberOfAyahs: 7, revelationType: "Meccan" },
  { number: 2, name: "سُورَةُ ٱلْبَقَرَةِ", englishName: "Al-Baqarah", englishNameTranslation: "The Cow", numberOfAyahs: 286, revelationType: "Medinan" },
  { number: 3, name: "سُورَةُ آلِ عِمْرَانَ", englishName: "Ali 'Imran", englishNameTranslation: "Family of Imran", numberOfAyahs: 200, revelationType: "Medinan" },
  { number: 4, name: "سُورَةُ ٱلنِّسَاءِ", englishName: "An-Nisa", englishNameTranslation: "The Women", numberOfAyahs: 176, revelationType: "Medinan" },
  { number: 5, name: "سُورَةُ ٱلْمَائِدَةِ", englishName: "Al-Ma'idah", englishNameTranslation: "The Table Spread", numberOfAyahs: 120, revelationType: "Medinan" },
  { number: 6, name: "سُورَةُ ٱلْأَنْعَامِ", englishName: "Al-An'am", englishNameTranslation: "The Cattle", numberOfAyahs: 165, revelationType: "Meccan" },
  { number: 7, name: "سُورَةُ ٱلْأَعْرَافِ", englishName: "Al-A'raf", englishNameTranslation: "The Heights", numberOfAyahs: 206, revelationType: "Meccan" },
  { number: 8, name: "سُورَةُ ٱلْأَنْفَالِ", englishName: "Al-Anfal", englishNameTranslation: "The Spoils of War", numberOfAyahs: 75, revelationType: "Medinan" },
  { number: 9, name: "سُورَةُ ٱلتَّوْبَةِ", englishName: "At-Tawbah", englishNameTranslation: "The Repentance", numberOfAyahs: 129, revelationType: "Medinan" },
  { number: 10, name: "سُورَةُ يُونُسَ", englishName: "Yunus", englishNameTranslation: "Jonah", numberOfAyahs: 109, revelationType: "Meccan" },
  { number: 11, name: "سُورَةُ هُودٍ", englishName: "Hud", englishNameTranslation: "Hud", numberOfAyahs: 123, revelationType: "Meccan" },
  { number: 12, name: "سُورَةُ يُوسُفَ", englishName: "Yusuf", englishNameTranslation: "Joseph", numberOfAyahs: 111, revelationType: "Meccan" },
  { number: 13, name: "سُورَةُ ٱلرَّعْدِ", englishName: "Ar-Ra'd", englishNameTranslation: "The Thunder", numberOfAyahs: 43, revelationType: "Medinan" },
  { number: 14, name: "سُورَةُ إِبْرَاهِيمَ", englishName: "Ibrahim", englishNameTranslation: "Abraham", numberOfAyahs: 52, revelationType: "Meccan" },
  { number: 15, name: "سُورَةُ ٱلْحِجْرِ", englishName: "Al-Hijr", englishNameTranslation: "The Rocky Tract", numberOfAyahs: 99, revelationType: "Meccan" },
  { number: 16, name: "سُورَةُ ٱلنَّحْلِ", englishName: "An-Nahl", englishNameTranslation: "The Bee", numberOfAyahs: 128, revelationType: "Meccan" },
  { number: 17, name: "سُورَةُ ٱلْإِسْرَاءِ", englishName: "Al-Isra", englishNameTranslation: "The Night Journey", numberOfAyahs: 111, revelationType: "Meccan" },
  { number: 18, name: "سُورَةُ ٱلْكَهْفِ", englishName: "Al-Kahf", englishNameTranslation: "The Cave", numberOfAyahs: 110, revelationType: "Meccan" },
  { number: 19, name: "سُورَةُ مَرْيَمَ", englishName: "Maryam", englishNameTranslation: "Mary", numberOfAyahs: 98, revelationType: "Meccan" },
  { number: 20, name: "سُورَةُ طه", englishName: "Taha", englishNameTranslation: "Ta-Ha", numberOfAyahs: 135, revelationType: "Meccan" },
  { number: 21, name: "سُورَةُ ٱلْأَنْبِيَاءِ", englishName: "Al-Anbiya", englishNameTranslation: "The Prophets", numberOfAyahs: 112, revelationType: "Meccan" },
  { number: 22, name: "سُورَةُ ٱلْحَجِّ", englishName: "Al-Hajj", englishNameTranslation: "The Pilgrimage", numberOfAyahs: 78, revelationType: "Medinan" },
  { number: 23, name: "سُورَةُ ٱلْمُؤْمِنُونَ", englishName: "Al-Mu'minun", englishNameTranslation: "The Believers", numberOfAyahs: 118, revelationType: "Meccan" },
  { number: 24, name: "سُورَةُ ٱلنُّورِ", englishName: "An-Nur", englishNameTranslation: "The Light", numberOfAyahs: 64, revelationType: "Medinan" },
  { number: 25, name: "سُورَةُ ٱلْفُرْقَانِ", englishName: "Al-Furqan", englishNameTranslation: "The Criterion", numberOfAyahs: 77, revelationType: "Meccan" },
  { number: 26, name: "سُورَةُ ٱلشُّعَرَاءِ", englishName: "Ash-Shu'ara", englishNameTranslation: "The Poets", numberOfAyahs: 227, revelationType: "Meccan" },
  { number: 27, name: "سُورَةُ ٱلنَّمْلِ", englishName: "An-Naml", englishNameTranslation: "The Ant", numberOfAyahs: 93, revelationType: "Meccan" },
  { number: 28, name: "سُورَةُ ٱلْقَصَصِ", englishName: "Al-Qasas", englishNameTranslation: "The Stories", numberOfAyahs: 88, revelationType: "Meccan" },
  { number: 29, name: "سُورَةُ ٱلْعَنْكَبُوتِ", englishName: "Al-'Ankabut", englishNameTranslation: "The Spider", numberOfAyahs: 69, revelationType: "Meccan" },
  { number: 30, name: "سُورَةُ ٱلرُّومِ", englishName: "Ar-Rum", englishNameTranslation: "The Romans", numberOfAyahs: 60, revelationType: "Meccan" },
  { number: 31, name: "سُورَةُ لُقْمَانَ", englishName: "Luqman", englishNameTranslation: "Luqman", numberOfAyahs: 34, revelationType: "Meccan" },
  { number: 32, name: "سُورَةُ ٱلسَّجْدَةِ", englishName: "As-Sajdah", englishNameTranslation: "The Prostration", numberOfAyahs: 30, revelationType: "Meccan" },
  { number: 33, name: "سُورَةُ ٱلْأَحْزَابِ", englishName: "Al-Ahzab", englishNameTranslation: "The Combined Forces", numberOfAyahs: 73, revelationType: "Medinan" },
  { number: 34, name: "سُورَةُ سَبَإٍ", englishName: "Saba", englishNameTranslation: "Sheba", numberOfAyahs: 54, revelationType: "Meccan" },
  { number: 35, name: "سُورَةُ فَاطِرٍ", englishName: "Fatir", englishNameTranslation: "Originator", numberOfAyahs: 45, revelationType: "Meccan" },
  { number: 36, name: "سُورَةُ يس", englishName: "Ya-Sin", englishNameTranslation: "Ya Sin", numberOfAyahs: 83, revelationType: "Meccan" },
  { number: 37, name: "سُورَةُ ٱلصَّافَّاتِ", englishName: "As-Saffat", englishNameTranslation: "Those who set the Ranks", numberOfAyahs: 182, revelationType: "Meccan" },
  { number: 38, name: "سُورَةُ ص", englishName: "Sad", englishNameTranslation: "The Letter Sad", numberOfAyahs: 88, revelationType: "Meccan" },
  { number: 39, name: "سُورَةُ ٱلزُّمَرِ", englishName: "Az-Zumar", englishNameTranslation: "The Troops", numberOfAyahs: 75, revelationType: "Meccan" },
  { number: 40, name: "سُورَةُ غَافِرٍ", englishName: "Ghafir", englishNameTranslation: "The Forgiver", numberOfAyahs: 85, revelationType: "Meccan" },
  { number: 41, name: "سُورَةُ فُصِّلَتْ", englishName: "Fussilat", englishNameTranslation: "Explained in Detail", numberOfAyahs: 54, revelationType: "Meccan" },
  { number: 42, name: "سُورَةُ ٱلشُّورَىٰ", englishName: "Ash-Shuraa", englishNameTranslation: "The Consultation", numberOfAyahs: 53, revelationType: "Meccan" },
  { number: 43, name: "سُورَةُ ٱلزُّخْرُفِ", englishName: "Az-Zukhruf", englishNameTranslation: "The Ornaments of Gold", numberOfAyahs: 89, revelationType: "Meccan" },
  { number: 44, name: "سُورَةُ ٱلدُّخَانِ", englishName: "Ad-Dukhan", englishNameTranslation: "The Smoke", numberOfAyahs: 59, revelationType: "Meccan" },
  { number: 45, name: "سُورَةُ ٱلْجَاثِيَةِ", englishName: "Al-Jathiyah", englishNameTranslation: "The Crouching", numberOfAyahs: 37, revelationType: "Meccan" },
  { number: 46, name: "سُورَةُ ٱلْأَحْقَافِ", englishName: "Al-Ahqaf", englishNameTranslation: "The Wind-Curved Sandhills", numberOfAyahs: 35, revelationType: "Meccan" },
  { number: 47, name: "سُورَةُ مُحَمَّدٍ", englishName: "Muhammad", englishNameTranslation: "Muhammad", numberOfAyahs: 38, revelationType: "Medinan" },
  { number: 48, name: "سُورَةُ ٱلْفَتْحِ", englishName: "Al-Fath", englishNameTranslation: "The Victory", numberOfAyahs: 29, revelationType: "Medinan" },
  { number: 49, name: "سُورَةُ ٱلْحُجُرَاتِ", englishName: "Al-Hujurat", englishNameTranslation: "The Dwellings", numberOfAyahs: 18, revelationType: "Medinan" },
  { number: 50, name: "سُورَةُ ق", englishName: "Qaf", englishNameTranslation: "The Letter Qaf", numberOfAyahs: 45, revelationType: "Meccan" },
  { number: 51, name: "سُورَةُ ٱلذَّارِيَاتِ", englishName: "Adh-Dhariyat", englishNameTranslation: "The Winnowing Winds", numberOfAyahs: 60, revelationType: "Meccan" },
  { number: 52, name: "سُورَةُ ٱلطُّورِ", englishName: "At-Tur", englishNameTranslation: "The Mount", numberOfAyahs: 49, revelationType: "Meccan" },
  { number: 53, name: "سُورَةُ ٱلنَّجْمِ", englishName: "An-Najm", englishNameTranslation: "The Star", numberOfAyahs: 62, revelationType: "Meccan" },
  { number: 54, name: "سُورَةُ ٱلْقَمَرِ", englishName: "Al-Qamar", englishNameTranslation: "The Moon", numberOfAyahs: 55, revelationType: "Meccan" },
  { number: 55, name: "سُورَةُ ٱلرَّحْمَٰنِ", englishName: "Ar-Rahman", englishNameTranslation: "The Beneficent", numberOfAyahs: 78, revelationType: "Medinan" },
  { number: 56, name: "سُورَةُ ٱلْوَاقِعَةِ", englishName: "Al-Waqi'ah", englishNameTranslation: "The Inevitable", numberOfAyahs: 96, revelationType: "Meccan" },
  { number: 57, name: "سُورَةُ ٱلْحَدِيدِ", englishName: "Al-Hadid", englishNameTranslation: "The Iron", numberOfAyahs: 29, revelationType: "Medinan" },
  { number: 58, name: "سُورَةُ ٱلْمُجَادِلَةِ", englishName: "Al-Mujadilah", englishNameTranslation: "The Pleading Woman", numberOfAyahs: 22, revelationType: "Medinan" },
  { number: 59, name: "سُورَةُ ٱلْحَشْرِ", englishName: "Al-Hashr", englishNameTranslation: "The Exile", numberOfAyahs: 24, revelationType: "Medinan" },
  { number: 60, name: "سُورَةُ ٱلْمُمْتَحَنَةِ", englishName: "Al-Mumtahanah", englishNameTranslation: "She that is to be examined", numberOfAyahs: 13, revelationType: "Medinan" },
  { number: 61, name: "سُورَةُ ٱلصَّفِّ", englishName: "As-Saff", englishNameTranslation: "The Ranks", numberOfAyahs: 14, revelationType: "Medinan" },
  { number: 62, name: "سُورَةُ ٱلْجُمُعَةِ", englishName: "Al-Jumu'ah", englishNameTranslation: "The Congregation", numberOfAyahs: 11, revelationType: "Medinan" },
  { number: 63, name: "سُورَةُ ٱلْمُنَافِقُونَ", englishName: "Al-Munafiqun", englishNameTranslation: "The Hypocrites", numberOfAyahs: 11, revelationType: "Medinan" },
  { number: 64, name: "سُورَةُ ٱلتَّغَابُنِ", englishName: "At-Taghabun", englishNameTranslation: "The Mutual Disillusion", numberOfAyahs: 18, revelationType: "Medinan" },
  { number: 65, name: "سُورَةُ ٱلطَّلَاقِ", englishName: "At-Talaq", englishNameTranslation: "The Divorce", numberOfAyahs: 12, revelationType: "Medinan" },
  { number: 66, name: "سُورَةُ ٱلتَّحْرِيمِ", englishName: "At-Tahrim", englishNameTranslation: "The Prohibition", numberOfAyahs: 12, revelationType: "Medinan" },
  { number: 67, name: "سُورَةُ ٱلْمُلْكِ", englishName: "Al-Mulk", englishNameTranslation: "The Sovereignty", numberOfAyahs: 30, revelationType: "Meccan" },
  { number: 68, name: "سُورَةُ ٱلْقَلَمِ", englishName: "Al-Qalam", englishNameTranslation: "The Pen", numberOfAyahs: 52, revelationType: "Meccan" },
  { number: 69, name: "سُورَةُ ٱلْحَاقَّةِ", englishName: "Al-Haqqah", englishNameTranslation: "The Reality", numberOfAyahs: 52, revelationType: "Meccan" },
  { number: 70, name: "سُورَةُ ٱلْمَعَارِجِ", englishName: "Al-Ma'arij", englishNameTranslation: "The Ascending Stairways", numberOfAyahs: 44, revelationType: "Meccan" },
  { number: 71, name: "سُورَةُ نُوحٍ", englishName: "Nuh", englishNameTranslation: "Noah", numberOfAyahs: 28, revelationType: "Meccan" },
  { number: 72, name: "سُورَةُ ٱلْجِنِّ", englishName: "Al-Jinn", englishNameTranslation: "The Jinn", numberOfAyahs: 28, revelationType: "Meccan" },
  { number: 73, name: "سُورَةُ ٱلْمُزَّمِّلِ", englishName: "Al-Muzzammil", englishNameTranslation: "The Enshrouded One", numberOfAyahs: 20, revelationType: "Meccan" },
  { number: 74, name: "سُورَةُ ٱلْمُدَّثِّرِ", englishName: "Al-Muddaththir", englishNameTranslation: "The Cloaked One", numberOfAyahs: 56, revelationType: "Meccan" },
  { number: 75, name: "سُورَةُ ٱلْقِيَامَةِ", englishName: "Al-Qiyamah", englishNameTranslation: "The Resurrection", numberOfAyahs: 40, revelationType: "Meccan" },
  { number: 76, name: "سُورَةُ ٱلْإِنْسَانِ", englishName: "Al-Insan", englishNameTranslation: "The Man", numberOfAyahs: 31, revelationType: "Medinan" },
  { number: 77, name: "سُورَةُ ٱلْمُرْسَلَاتِ", englishName: "Al-Mursalat", englishNameTranslation: "The Emissaries", numberOfAyahs: 50, revelationType: "Meccan" },
  { number: 78, name: "سُورَةُ ٱلنَّبَإِ", englishName: "An-Naba", englishNameTranslation: "The Tidings", numberOfAyahs: 40, revelationType: "Meccan" },
  { number: 79, name: "سُورَةُ ٱلنَّازِعَاتِ", englishName: "An-Naziat", englishNameTranslation: "Those who drag forth", numberOfAyahs: 46, revelationType: "Meccan" },
  { number: 80, name: "سُورَةُ عَبَسَ", englishName: "Abasa", englishNameTranslation: "He frowned", numberOfAyahs: 42, revelationType: "Meccan" },
  { number: 81, name: "سُورَةُ ٱلتَّكْوِيرِ", englishName: "At-Takwir", englishNameTranslation: "The Overthrowing", numberOfAyahs: 29, revelationType: "Meccan" },
  { number: 82, name: "سُورَةُ ٱلْإِنْفِطَارِ", englishName: "Al-Infitar", englishNameTranslation: "The Cleaving", numberOfAyahs: 19, revelationType: "Meccan" },
  { number: 83, name: "سُورَةُ ٱلْمُطَفِّفِينَ", englishName: "Al-Mutaffifin", englishNameTranslation: "Defrauding", numberOfAyahs: 36, revelationType: "Meccan" },
  { number: 84, name: "سُورَةُ ٱلْإِنْشِقَاقِ", englishName: "Al-Inshiqaq", englishNameTranslation: "The Splitting Open", numberOfAyahs: 25, revelationType: "Meccan" },
  { number: 85, name: "سُورَةُ ٱلْبُرُوجِ", englishName: "Al-Buruj", englishNameTranslation: "The Mansions of the Stars", numberOfAyahs: 22, revelationType: "Meccan" },
  { number: 86, name: "سُورَةُ ٱلطَّارِقِ", englishName: "At-Tariq", englishNameTranslation: "The Morning Star", numberOfAyahs: 17, revelationType: "Meccan" },
  { number: 87, name: "سُورَةُ ٱلْأَعْلَىٰ", englishName: "Al-A'la", englishNameTranslation: "The Most High", numberOfAyahs: 19, revelationType: "Meccan" },
  { number: 88, name: "سُورَةُ ٱلْغَاشِيَةِ", englishName: "Al-Ghashiyah", englishNameTranslation: "The Overwhelming", numberOfAyahs: 26, revelationType: "Meccan" },
  { number: 89, name: "سُورَةُ ٱلْفَجْرِ", englishName: "Al-Fajr", englishNameTranslation: "The Dawn", numberOfAyahs: 30, revelationType: "Meccan" },
  { number: 90, name: "سُورَةُ ٱلْبَلَدِ", englishName: "Al-Balad", englishNameTranslation: "The City", numberOfAyahs: 20, revelationType: "Meccan" },
  { number: 91, name: "سُورَةُ ٱلشَّمْسِ", englishName: "Ash-Shams", englishNameTranslation: "The Sun", numberOfAyahs: 15, revelationType: "Meccan" },
  { number: 92, name: "سُورَةُ ٱللَّيْلِ", englishName: "Al-Layl", englishNameTranslation: "The Night", numberOfAyahs: 21, revelationType: "Meccan" },
  { number: 93, name: "سُورَةُ ٱلضُّحَىٰ", englishName: "Ad-Duha", englishNameTranslation: "The Morning Hours", numberOfAyahs: 11, revelationType: "Meccan" },
  { number: 94, name: "سُورَةُ ٱلشَّرْحِ", englishName: "Ash-Sharh", englishNameTranslation: "The Consolation", numberOfAyahs: 8, revelationType: "Meccan" },
  { number: 95, name: "سُورَةُ ٱلتِّينِ", englishName: "At-Tin", englishNameTranslation: "The Fig", numberOfAyahs: 8, revelationType: "Meccan" },
  { number: 96, name: "سُورَةُ ٱلْعَلَقِ", englishName: "Al-'Alaq", englishNameTranslation: "The Clot", numberOfAyahs: 19, revelationType: "Meccan" },
  { number: 97, name: "سُورَةُ ٱلْقَدْرِ", englishName: "Al-Qadr", englishNameTranslation: "The Power", numberOfAyahs: 5, revelationType: "Meccan" },
  { number: 98, name: "سُورَةُ ٱلْبَيِّنَةِ", englishName: "Al-Bayyinah", englishNameTranslation: "The Clear Proof", numberOfAyahs: 8, revelationType: "Medinan" },
  { number: 99, name: "سُورَةُ ٱلزَّلْزَلَةِ", englishName: "Az-Zalzalah", englishNameTranslation: "The Earthquake", numberOfAyahs: 8, revelationType: "Medinan" },
  { number: 105, name: "سُورَةُ ٱلْفِيلِ", englishName: "Al-Fil", englishNameTranslation: "The Elephant", numberOfAyahs: 5, revelationType: "Meccan" },
  { number: 106, name: "سُورَةُ قُرَيْشٍ", englishName: "Quraysh", englishNameTranslation: "Quraysh", numberOfAyahs: 4, revelationType: "Meccan" },
  { number: 107, name: "سُورَةُ ٱلْمَاعُونَ", englishName: "Al-Ma'un", englishNameTranslation: "The Small Kindnesses", numberOfAyahs: 7, revelationType: "Meccan" },
  { number: 108, name: "سُورَةُ ٱلْكَوْثَرِ", englishName: "Al-Kawthar", englishNameTranslation: "The Abundance", numberOfAyahs: 3, revelationType: "Meccan" },
  { number: 109, name: "سُورَةُ ٱلْكَافِرُونَ", englishName: "Al-Kafirun", englishNameTranslation: "The Disbelievers", numberOfAyahs: 6, revelationType: "Meccan" },
  { number: 110, name: "سُورَةُ ٱلنَّصْرِ", englishName: "An-Nasr", englishNameTranslation: "The Divine Support", numberOfAyahs: 3, revelationType: "Medinan" },
  { number: 111, name: "سُورَةُ ٱلْمَسَدِ", englishName: "Al-Masad", englishNameTranslation: "The Palm Fiber", numberOfAyahs: 5, revelationType: "Meccan" },
  { number: 112, name: "سُورَةُ ٱلْإِخْلَاصِ", englishName: "Al-Ikhlas", englishNameTranslation: "The Sincerity", numberOfAyahs: 4, revelationType: "Meccan" },
  { number: 113, name: "سُورَةُ ٱلْفَلَقِ", englishName: "Al-Falaq", englishNameTranslation: "The Daybreak", numberOfAyahs: 5, revelationType: "Meccan" },
  { number: 114, name: "سُورَةُ ٱلنَّاسِ", englishName: "An-Nas", englishNameTranslation: "The Mankind", numberOfAyahs: 6, revelationType: "Meccan" }
];
